INSERT INTO VIZSGAIDOPONT
SELECT RAND.RANDDATE, C.CODE, C.CLASSROOM_ID, 0, 50 FROM COURSE C
LEFT JOIN (SELECT TO_DATE(TRUNC(DBMS_RANDOM.VALUE(TO_CHAR(DATE '2017-01-01','J'), TO_CHAR(DATE '2017-12-31','J'))),'J') RANDDATE FROM DUAL) 
RAND ON 1=1
WHERE C.CLASSROOM_ID NOT LIKE '%NAN%';

UPDATE VIZSGAIDOPONT SET DATUM= TO_DATE(TRUNC(DBMS_RANDOM.value(TO_CHAR(date '2017-01-01','J'),TO_CHAR(SYSDATE,'J'))),'J');